<li><a href="http://www.recettes-asselin.com/recettes/plats/Boeuf-auX-carottes.php">Bœuf auX carottes</a></li>
<li><a href="http://www.recettes-asselin.com/recettes/plats/Bouilli-de-orise.php">Bouilli de Orise</a></li>
<li><a href="http://www.recettes-asselin.com/recettes/plats/cabbage_rolls.php">Cabbage rolls</a></li>
<li><a href="http://www.recettes-asselin.com/recettes/plats/Chili_Con_Carne_Jovette.php">Chili con carne (Jovette)</a></li>
<li><a href="http://www.recettes-asselin.com/recettes/plats/ChiliMac.php">Chili Mac de Jovette</a></li>
<li><a href="http://www.recettes-asselin.com/recettes/plats/Crevettes_sophie.php">Crevettes (Sophie)</a></li>
<li><a href="http://www.recettes-asselin.com/recettes/plats/ChiliMac.php">ChiliMac (Jovette)</a></li>
<li><a href="http://www.recettes-asselin.com/recettes/plats/deviled_fried_chicken.php">Devilled Fried Chicken</a></li>
<li><a href="http://www.recettes-asselin.com/recettes/plats/dinde_lory.php">Dinde à la Lori</a></li>
<li><a href="http://www.recettes-asselin.com/recettes/plats/fauxveauparmesan.php">Faux veau parmesan</a></li>
<li><a href="http://www.recettes-asselin.com/recettes/plats/feves-au-lard.php">Fèves au lard</a></li>
<li><a href="http://www.recettes-asselin.com/recettes/plats/filet_de_porc_sophie.php">Filet de porc (Sophie)</a></li>
<li><a href="http://www.recettes-asselin.com/recettes/plats/lamb_tourtiere.php">Lamb Tourtière</a></li>
<li><a href="http://www.recettes-asselin.com/recettes/plats/london_broil.php">London broil</a></li>
<li><a href="http://www.recettes-asselin.com/recettes/plats/OssoBuco.php">Osso Buco</a></li>
<li><a href="http://www.recettes-asselin.com/recettes/plats/pain-de-viande-sophie.php">Pain de viande (Sophie)</a></li>
<li><a href="http://www.recettes-asselin.com/recettes/plats/patates-aux-saumon.php">Patates aux saumon</a></li>
<li><a href="http://www.recettes-asselin.com/recettes/plats/pate_chinois.php">Pâté chinois</a></li>
<li><a href="http://www.recettes-asselin.com/recettes/plats/pate_favori_des_enfants.php">Pâté favori des enfants</a></li>
<li><a href="http://www.recettes-asselin.com/recettes/plats/pats-stew.php">Pat’s Beef Stew</a></li>
<li><a href="http://www.recettes-asselin.com/recettes/plats/peanut_But_Steak_Surpr.php">Peanut butter steak de Yves</a></li>
<li><a href="http://www.recettes-asselin.com/recettes/plats/porc-epic.php">Porc-Épic</a></li>
<li><a href="http://www.recettes-asselin.com/recettes/plats/Porc-chops-de-sophie.php">Porc Chops de Sophie</a></li>
<li><a href="http://www.recettes-asselin.com/recettes/plats/pork_tenderloin_mom.php">Pork Tenderloin de Mom</a></li>
<li><a href="http://www.recettes-asselin.com/recettes/plats/pork_tenderloin.php">Pork Tenderloin de Sophie</a></li>
<li><a href="http://www.recettes-asselin.com/recettes/plats/Poulet-au-40-gousses-dail.php">Poulet aux 40 gousses d’ail</a></li>
<li><a href="http://www.recettes-asselin.com/recettes/plats/poulet-claudia.php">Poulet de Claudia</a></li>
<li><a href="http://www.recettes-asselin.com/recettes/plats/poulet_provencale.php">Poulet à la provençale de Philippe</a></li>
<li><a href="http://www.recettes-asselin.com/recettes/plats/poulet_sophie.php">Poulet au four de Sophie</a></li>
<li><a href="http://www.recettes-asselin.com/recettes/plats/poulet_asperges.php">Poulet et asperges en casserole</a></li>
<li><a href="http://www.recettes-asselin.com/recettes/plats/serge-pulled-pork.php">Pulled Pork – Serge’s</a></li>
<li><a href="http://www.recettes-asselin.com/recettes/plats/ragout_de_boulettes_Sophie.php">Ragoût de boulettes et de pattes de cochon</a></li>
<li><a href="http://www.recettes-asselin.com/recettes/plats/roast-beef-sophie.php">Roast Beef (Sophie)</a></li>
<li><a href="http://www.recettes-asselin.com/recettes/plats/Roast_potato_ragout.php">Roast &amp; Potato Ragu</a></li>
<li><a href="http://www.recettes-asselin.com/recettes/plats/savoury_pepper_steak.php">Savoury Pepper Steak</a></li>
<li><a href="http://www.recettes-asselin.com/recettes/plats/vol-au-vents.php">Vols au vents</a></li>